version: '3.4'

services:
  dealproject:
    image: ${DOCKER_REGISTRY-}dealproject
    build:
      context: .
      dockerfile: DealProject/DealProject/Dockerfile
    ports:
      - "10001:80"
  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: AuthService/AuthService/Dockerfile
    ports:
      - "10002:80"
  dealproject-db:
    image: postgres
    container_name: dealproject-db
    user: postgres
    restart: always
    secrets:
      - dealproject-db-password
    volumes:
      - dealproject-db-data:/var/lib/postgresal/data
    environment:
      - POSTGRES_DB=dealproject
#      - POSTGRES_PASSWORD_FILE=/run/secrets/dealproject-db-password
      - POSTGRES_USER=dealproject
      - POSTGRES_PASSWORD=1234
    expose:
      - "8001:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  authservice-db:
    image: postgres
    container_name: authservice-db
    user: postgres
    restart: always
    secrets:
      - authservice-db-password
    volumes:
      - authservice-db-data:/var/lib/postgresal/data
    environment:
      - POSTGRES_DB=authservice
#      - POSTGRES_PASSWORD_FILE=/run/secrets/authservice-db-password
      - POSTGRES_USER=authservice
      - POSTGRES_PASSWORD=1234
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  dealproject-db-data:    
  authservice-db-data:
secrets:
  dealproject-db-password:
    file: Secrets/dealproject-db-password.txt
  authservice-db-password:
    file: Secrets/authservice-db-password.txt