version: '3.4'

services:
  dealproject:
    image: ${DOCKER_REGISTRY-}dealproject
    build:
      context: .
      dockerfile: DealProject/Dockerfile
    ports:
      - "10001:80"
  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "10002:80"
